services:
  tailscale-portainer-ce:
    image: tailscale/tailscale:latest
    container_name: tailscale-portainer-ce
    hostname: portainer
    environment:
      - TS_AUTHKEY=<TAILSCALE_AUTH_KEY>
      - "TS_EXTRA_ARGS=--advertise-tags=tag:node --reset"
      - TS_SERVE_CONFIG=/config/portainer.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  portainer-ce:
      container_name: portainer-ce
      network_mode: service:tailscale-portainer-ce
      restart: unless-stopped
      depends_on:
        - tailscale-portainer-ce
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      image: portainer/portainer-ce:lts
      environment:
        - TZ=Europe/Stockholm

volumes:
  portainer_data:
    driver: local
  tailscale-portainer-ce:
    driver: local