name: Main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: 'write'
  checks: 'write'
  contents: 'write'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'
  statuses: 'write'

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build
        run: echo "Building the project..."