name: Source protection

on:
  workflow_call:

permissions:
  contents: 'read'
  pull-requests: 'read'
  checks: 'write'

jobs:
  validate-commits:
    name: Validate Commits
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Commmit lint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed
        with:
          configFile: .github/commitlint.config.cjs
          failOnErrors: true
          failOnWarnings: false
  lint:
    name: Lint
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Setup  Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Markdown lint
        run: npm run lint:markdown
      - name: YAML lint
        run: npm run lint:yaml


